name: Build Qt App

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Qt (MSVC Instead of MinGW)
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.6.2
        arch: win64_msvc2019_64

    - name: Configure project (MSVC)
      run: |
        cmake -B build -S . -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Deploy Qt dependencies
      run: |
        windeployqt build/Release/nafuda.exe --release

    - name: Upload Artifact (.exe + DLL)
      uses: actions/upload-artifact@v4
      with:
        name: nafuda-windows
        path: build/Release
